#!/usr/bin/env node
import { Command } from 'commander'
import chalk from 'chalk'
import ora from 'ora'
import { createInterface } from 'node:readline'
import { writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { loadConfig, validateConfig, isFirstRun, isPlatformManaged, getSupportedTaskModes, type MinerConfig } from './config.js'
import { autoAuthenticate, type AuthResult } from './auth.js'
import { pollForTask, requestPayloadFromOracle, submitPayload, submitLocalComputeResult, type TaskData, type SubmitResult } from './poller.js'
import { generatePayload } from './llm/provider.js'
import { executeLocally } from './local-sandbox/executor.js'
import { buildSubmissionBody } from './local-sandbox/proof.js'
import * as tier1 from './llm/prompts/tier1-token-injection.js'
import * as tier2 from './llm/prompts/tier2-social-engineering.js'
import * as tier3 from './llm/prompts/tier3-memory-poisoning.js'

const BANNER = chalk.cyan(`
  ███████╗██╗  ██╗███████╗██╗     ██╗
  ██╔════╝██║  ██║██╔════╝██║     ██║
  ███████╗███████║█████╗  ██║     ██║
  ╚════██║██╔══██║██╔══╝  ██║     ██║
  ███████║██║  ██║███████╗███████╗███████╗
  ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
`)

const program = new Command()

program
  .name('shell-miner')
  .description('$SHELL Protocol Miner CLI — Mine $SHELL by red-teaming AI agents')
  .version('0.2.1')

// ── Setup command (interactive first-run wizard) ──────────────────────────────

program
  .command('setup')
  .description('Interactive setup wizard — configure your miner in 2 minutes')
  .action(async () => {
    console.log(BANNER)
    console.log(chalk.cyan('  Miner Setup Wizard'))
    console.log()
    console.log(chalk.gray('  This wizard will create a .env file with your configuration.'))
    console.log()

    const rl = createInterface({ input: process.stdin, output: process.stdout })
    const ask = (question: string): Promise<string> =>
      new Promise(resolve => rl.question(question, resolve))

    // Step 1: Auth
    console.log(chalk.bold('Step 1: 获取你的 $SHELL 密钥'))
    console.log(chalk.gray('  前往 https://openshell.cc → 注册 → 控制面板 → Agent 注册'))
    console.log(chalk.gray('  复制生成的 sk-shell-xxx 密钥'))
    console.log()
    const shellApiKey = (await ask(chalk.white('  SHELL_API_KEY (sk-shell-xxx): '))).trim()

    // Step 2: Optional advanced local model
    console.log()
    console.log(chalk.bold('Step 2: 高级本地模型（可选）'))
    console.log(chalk.cyan('  直接回车即可') + chalk.gray(' — 默认使用平台 AI 生成 payload，无需第三方 API Key'))
    console.log(chalk.gray('  如果你想参与高级本地计算任务，可填写自己的 LLM Key：'))
    console.log(chalk.gray('    Anthropic → console.anthropic.com  (claude-haiku-4-5)'))
    console.log(chalk.gray('    DeepSeek  → platform.deepseek.com  (deepseek-chat, 最便宜)'))
    console.log(chalk.gray('    OpenAI    → platform.openai.com    (gpt-4o-mini)'))
    console.log()
    const llmApiKey = (await ask(chalk.white('  LLM_API_KEY（留空跳过）: '))).trim()

    let llmProvider = 'anthropic'
    if (llmApiKey) {
      if (llmApiKey.startsWith('sk-proj-')) llmProvider = 'openai'
      else if (llmApiKey.startsWith('sk-ant-') || llmApiKey.startsWith('sk-')) llmProvider = 'anthropic'
      else {
        console.log()
        console.log(chalk.gray('  LLM provider: 1) Anthropic  2) OpenAI  3) DeepSeek'))
        const pChoice = (await ask(chalk.white('  Choose [1]: '))).trim() || '1'
        llmProvider = { '1': 'anthropic', '2': 'openai', '3': 'deepseek' }[pChoice] || 'anthropic'
      }
    }

    rl.close()

    // Write .env
    const envPath = resolve(process.cwd(), '.env')
    const envContent = [
      '# $SHELL Miner Configuration — generated by shell-miner setup',
      '',
      '# Oracle endpoint',
      'ORACLE_URL=https://oracle.openshell.cc',
      '',
      '# Authentication',
      shellApiKey ? `SHELL_API_KEY=${shellApiKey}` : '# SHELL_API_KEY=sk-shell-...',
      '# WALLET_PRIVATE_KEY=  # 可选：Solana 钱包',
      '',
      '# Optional advanced local model',
      llmApiKey ? `LLM_PROVIDER=${llmProvider}` : '# LLM_PROVIDER=anthropic',
      llmApiKey ? `LLM_API_KEY=${llmApiKey}` : '# LLM_API_KEY=',
      '',
      '# Mining',
      `EXECUTION_MODE=${llmApiKey ? 'auto' : 'sandbox_only'}`,
      'POLLING_INTERVAL_MS=5000',
    ].join('\n')

    writeFileSync(envPath, envContent)
    console.log()
    console.log(chalk.green('  ✓ Configuration saved to .env'))
    console.log()
    console.log(chalk.cyan('  Start mining:'), chalk.white('npx @openshell-cc/miner-cli start'))
    console.log()
  })

// ── Start command ─────────────────────────────────────────────────────────────

program
  .command('start')
  .description('Start mining (authenticate, poll tasks, generate payloads, submit)')
  .option('-r, --referral <code>', 'Referral code from another miner')
  .action(async (opts) => {
    const config = loadConfig()

    // First-run: guide user to setup wizard
    if (isFirstRun(config)) {
      console.log(BANNER)
      console.log(chalk.yellow('  未找到配置文件！'))
      console.log()
      console.log(chalk.white('  运行配置向导（2 分钟完成）：'))
      console.log(chalk.cyan('    npx @openshell-cc/miner-cli setup'))
      console.log()
      console.log(chalk.gray('  或手动创建 .env 文件：'))
      console.log(chalk.gray('    SHELL_API_KEY=sk-shell-xxx  ← 在 https://openshell.cc/dashboard 获取'))
      console.log(chalk.gray('    # LLM_API_KEY=sk-ant-...  ← 可选，仅用于高级本地计算模式'))
      console.log(chalk.gray('    ORACLE_URL=https://oracle.openshell.cc'))
      console.log()
      process.exit(0)
    }

    const errors = validateConfig(config)
    if (errors.length > 0) {
      console.error(chalk.red('\n  Configuration errors:\n'))
      errors.forEach(e => {
        const lines = e.split('\n')
        console.error(chalk.red(`  ✗ ${lines[0]}`))
        lines.slice(1).forEach(l => console.error(chalk.gray(`    ${l}`)))
      })
      console.error()
      console.error(chalk.gray('  Run `npx @openshell-cc/miner-cli setup` to configure interactively.'))
      console.error()
      process.exit(1)
    }

    console.log(BANNER)
    console.log(chalk.cyan('  Decentralized AI Red Team Network'))
    const authMethod = config.shellApiKey ? 'API Key' : 'Solana Wallet'
    const modeLabel = isPlatformManaged(config)
      ? chalk.cyan('platform_managed') + chalk.gray(' (零第三方 API Key)')
      : chalk.magenta(config.executionMode) + chalk.gray(` (${config.llmProvider}/${config.llmModel})`)
    console.log(chalk.gray(`  Oracle:  ${config.oracleUrl}`))
    console.log(chalk.gray(`  Auth:    ${authMethod}`))
    console.log(`  ${chalk.gray('Mode:')}   ${modeLabel}`)
    if (isPlatformManaged(config)) {
      console.log(chalk.gray('  ') + chalk.green('✓') + chalk.gray(' 平台 AI 负责生成 payload；Claude/OpenClaw/antigravity 订阅用户也可零 API 参与'))
    } else {
      console.log(chalk.gray('  ') + chalk.green('✓') + chalk.gray(' 已开启高级本地模型模式，可参与更多本地计算任务'))
    }
    console.log()

    // Authenticate
    const authSpinner = ora('Authenticating with Oracle...').start()
    let token: string
    let user: AuthResult['user']

    try {
      const result = await autoAuthenticate(config, opts.referral)
      token = result.token
      user = result.user
      const identity = user.agentName || (user.walletAddress ? `${user.walletAddress.slice(0, 8)}...` : 'unknown')
      authSpinner.succeed(
        `Authenticated as ${chalk.green(identity)} | Tier: ${chalk.yellow(user.tier)} | Points: ${chalk.cyan(user.shellPoints)}`,
      )
      console.log(chalk.gray(`  Your referral code: ${user.referralCode}`))
    }
    catch (err) {
      authSpinner.fail(`Authentication failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
      process.exit(1)
    }

    console.log()
    console.log(chalk.green('  Mining started.'), chalk.gray('Press Ctrl+C to stop.'))
    console.log()

    // Mining loop
    let totalTasks = 0
    let totalSuccess = 0
    let totalPoints = 0

    while (true) {
      const pollSpinner = ora('Polling for tasks...').start()

      try {
        const task = await pollForTask(config, token, getSupportedTaskModes(config))

        if (!task) {
          pollSpinner.info('No tasks available. Waiting...')
          await sleep(config.pollingIntervalMs)
          continue
        }

        const isLocalCompute = task.executionMode === 'local_compute'
        const modeTag = isLocalCompute ? chalk.magenta('[LOCAL]') : chalk.blue('[SANDBOX]')

        pollSpinner.succeed(`${modeTag} Task: ${chalk.yellow(task.taskType)} | Chain: ${chalk.blue(task.targetChain)} | Difficulty: ${'★'.repeat(task.difficulty)} | Reward: ${chalk.cyan(task.rewardPoints)} pts`)

        // Execution mode routing
        if (config.executionMode === 'local_only' && !isLocalCompute) {
          console.log(chalk.gray('  [local_only] Skipping sandbox task...'))
          await sleep(config.pollingIntervalMs)
          continue
        }
        if (config.executionMode === 'sandbox_only' && isLocalCompute) {
          console.log(chalk.gray('  [sandbox_only] Skipping local_compute task...'))
          await sleep(config.pollingIntervalMs)
          continue
        }

        let result: SubmitResult

        if (isLocalCompute) {
          result = await handleLocalCompute(config, token, task)
        }
        else {
          result = await handleSandboxVerified(config, token, task)
        }

        totalTasks++

        if (result.result === 'success') {
          totalSuccess++
          totalPoints += result.pointsAwarded ?? 0
          console.log(chalk.green(`  ✓ Attack successful! +${result.pointsAwarded} pts`))
        }
        else if (result.result === 'slashed') {
          console.log(chalk.red(`  ✗ SLASHED! ${result.message}`))
        }
        else if (result.result === 'failed') {
          console.log(chalk.red(`  ✗ Failed: ${result.message}`))
        }
        else {
          const spotTag = result.spotCheckSelected ? chalk.yellow(' [spot-check pending]') : ''
          console.log(chalk.gray(`  ~ Submitted for verification.${spotTag}`))
        }

        const rate = totalTasks > 0 ? (totalSuccess / totalTasks * 100).toFixed(1) : '0.0'
        console.log(chalk.gray(`  [Stats] Tasks: ${totalTasks} | Success: ${totalSuccess} (${rate}%) | Total pts: ${totalPoints}`))
        console.log()
      }
      catch (err) {
        pollSpinner.fail(`Error: ${err instanceof Error ? err.message : 'Unknown'}`)

        if (err instanceof Error && (err.message.includes('Token expired') || err.message.includes('re-authenticate') || err.message.includes('Invalid or expired'))) {
          if (config.walletPrivateKey) {
            console.log(chalk.yellow('  Re-authenticating...'))
            try {
              const result = await autoAuthenticate(config, opts.referral)
              token = result.token
              console.log(chalk.green('  Re-authenticated successfully'))
            }
            catch (authErr) {
              console.error(chalk.red(`  Re-auth failed: ${authErr instanceof Error ? authErr.message : 'Unknown'}`))
            }
          }
        }
      }

      await sleep(config.pollingIntervalMs)
    }
  })

// ── Status command ────────────────────────────────────────────────────────────

program
  .command('status')
  .description('Check your mining stats')
  .action(async () => {
    const config = loadConfig()
    const errors = validateConfig(config)
    if (errors.length > 0) {
      console.error(chalk.red('Configuration error — run `setup` first.'))
      process.exit(1)
    }

    const spinner = ora('Fetching stats...').start()
    try {
      const { token, user } = await autoAuthenticate(config)
      const res = await fetch(`${config.oracleUrl}/leaderboard/me`, {
        headers: { Authorization: `Bearer ${token}` },
      })
      const data = await res.json() as Record<string, unknown>
      spinner.stop()

      const identity = user.agentName || (user.walletAddress ? `${user.walletAddress.slice(0, 8)}...` : 'Agent')
      console.log()
      console.log(chalk.cyan('$SHELL Miner Status'))
      console.log(chalk.gray('─'.repeat(40)))
      console.log(chalk.white('  Identity:   '), chalk.green(identity))
      console.log(chalk.white('  Tier:       '), chalk.yellow(String(data.tier ?? user.tier)))
      console.log(chalk.white('  Points:     '), chalk.cyan(String(data.shellPoints ?? user.shellPoints)))
      console.log(chalk.white('  Success:    '), String(data.totalSuccessfulAttacks ?? '—'), '/', String(data.totalTasksCompleted ?? '—'))
      console.log(chalk.white('  Rate:       '), String(data.successRate ?? '—'))
      console.log(chalk.white('  Referral:   '), String(data.referralCode ?? user.referralCode))
      console.log()
    }
    catch (err) {
      spinner.fail(`Failed: ${err instanceof Error ? err.message : 'Unknown error'}`)
      process.exit(1)
    }
  })

// ── Prevent silent crashes ────────────────────────────────────────────────────

process.on('unhandledRejection', (err) => {
  console.error(chalk.red('Unhandled error:'), err)
})

program.parse()

// ── Helpers ───────────────────────────────────────────────────────────────────

async function handleLocalCompute(
  config: ReturnType<typeof loadConfig>,
  token: string,
  task: TaskData,
): Promise<SubmitResult> {
  const genSpinner = ora('Generating attack payload...').start()
  const { systemPrompt, userPrompt } = buildPrompts(task)
  const payloadResponse = await generatePayload(config, systemPrompt, userPrompt)
  const payload = payloadResponse.text
  genSpinner.succeed(`Payload generated (${payloadResponse.tokensUsed.input + payloadResponse.tokensUsed.output} tokens)`)

  const execSpinner = ora('Executing locally against target agent...').start()
  const executionResult = await executeLocally(
    config,
    task.targetAgentProfile,
    payload,
    task.mockToolDefinitions,
  )
  const totalTokens = executionResult.tokensUsed.input + executionResult.tokensUsed.output
  execSpinner.succeed(
    `Local execution: ${executionResult.actionLog.length} actions, ${executionResult.rounds} rounds, ${totalTokens} tokens`,
  )

  const subSpinner = ora('Submitting result...').start()
  const body = buildSubmissionBody(
    task.id,
    payload,
    task.challengeNonce!,
    executionResult,
    config,
  )
  const result = await submitLocalComputeResult(config, token, body)
  subSpinner.stop()
  return result
}

async function handleSandboxVerified(
  config: ReturnType<typeof loadConfig>,
  token: string,
  task: TaskData,
): Promise<SubmitResult> {
  const genSpinner = ora('Generating attack payload...').start()
  const response = await requestPayloadFromOracle(config, token, task.id)
  const payload = response.payload
  genSpinner.succeed(`Platform AI generated payload (${payload.length} chars)`)

  const subSpinner = ora('Submitting to Oracle sandbox...').start()
  const result = await submitPayload(config, token, task.id, payload)
  subSpinner.stop()
  return result
}

function buildPrompts(task: TaskData): { systemPrompt: string, userPrompt: string } {
  const profile = task.targetAgentProfile
  const taskInfo = {
    targetAgentType: profile.name,
    targetChain: task.targetChain,
    defenseLevel: profile.defenseLevel,
    objective: `Trigger unauthorized action on ${profile.name}`,
    injectionSurface: task.injectionSurface,
  }

  switch (task.taskType) {
    case 'token_injection':
      return { systemPrompt: tier1.SYSTEM_PROMPT, userPrompt: tier1.buildUserPrompt(taskInfo) }
    case 'social_engineering':
      return { systemPrompt: tier2.SYSTEM_PROMPT, userPrompt: tier2.buildUserPrompt(taskInfo) }
    case 'memory_poisoning':
      return { systemPrompt: tier3.SYSTEM_PROMPT, userPrompt: tier3.buildUserPrompt(taskInfo) }
    case 'full_chain':
    default:
      return {
        systemPrompt: tier1.SYSTEM_PROMPT,
        userPrompt: tier1.buildUserPrompt({
          ...taskInfo,
          objective: `Full chain exploit: reconnaissance → injection → exploitation on ${profile.name}`,
        }),
      }
  }
}

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms))
}
